# Site settings
title: The Book of CSS3, 2nd Edition
author: Peter Gasston
email: peter@broken-links.com
description: > # this means to ignore newlines until "baseurl:"
  Companion site for The Book of CSS3 by Peter Gasston for No Starch Press. Example files, updates, and errata.
baseurl: "/thebookofcss3" # the subpath of your site, e.g. /blog/
url: "http://stopsatgreen.github.io/thebookofcss3" # the base hostname & protocol for your site
paginate: 10

# Author settings
twitter_username: stopsatgreen
github_username:  stopsatgreen

# Build settings
markdown: kramdown
